id: 6dfc9ca8dc9c41539ba7da013a6f8247
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_522-The_Dharani_of_the_Tathagata_Jnanolka-v1
  language: bo
  author: ''
  volume: {}
